### ISSUE TITLE
ObjectStorageSink: Error with float value in timePerObject parameter

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.objectstorage#155]
Exception in thread "Thread-11" java.lang.NumberFormatException: For input string: "5.5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:76)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:627)
	at com.ibm.streamsx.objectstorage.Utils.getParamSingleIntValue(Utils.java:141)
	at com.ibm.streamsx.objectstorage.internal.sink.OSObjectFactory.<init>(OSObjectFactory.java:53)
	at com.ibm.streamsx.objectstorage.BaseObjectStorageSink.initialize(BaseObjectStorageSink.java:1129)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:745)
	at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:277)

**Comment by markheger** [comment]
Workaround: Do apply values with 0 decimal place.
30.0 instead of 30.5
