### ISSUE TITLE
iss#9-stocator-based-impl: NPE if object has no expiry

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.objectstorage#27]
Exception in thread "Thread-18" java.lang.NullPointerException: Null expiry
	at org.ehcache.config.builders.CacheConfigurationBuilder.withExpiry(CacheConfigurationBuilder.java:294)
	at com.ibm.streamsx.objectstorage.OSObjectRegistry.<init>(OSObjectRegistry.java:140)
	at com.ibm.streamsx.objectstorage.BaseObjectStorageSink.initialize(BaseObjectStorageSink.java:885)
	at com.ibm.streamsx.objectstorage.s3.S3ObjectStorageSink.initialize(S3ObjectStorageSink.java:39)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:736)
	at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:274)

**Comment by markheger** [comment]
/com.ibm.streamsx.objectstorage/impl/java/src/com/ibm/streamsx/objectstorage/OSObjectRegistry.java
Expiry<Object, Object> expiry = null;
In the "if/elseif" block the "else" is missing. Therefore the case is causing the NullPointerException

**Comment by markheger** [comment]
com.ibm.streamsx.objectstorage.s3.sample ReadWriteSample
