### ISSUE TITLE
iss#9-stocator-based-impl:BucketScanSample failed

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.objectstorage#28]
Checking variables in object name 'output_%TIME.txt'
Checking object name section '%TIME.txt' validity
com.ibm.tools.attach.AttachNotSupportedException: target not found
	at com.ibm.tools.attach.javaSE.VirtualMachineImpl.attachTarget(VirtualMachineImpl.java:87)
	at com.ibm.tools.attach.javaSE.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:37)
	at ibm.tools.attach.J9AttachProvider.attachVirtualMachine(J9AttachProvider.java:55)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.ehcache.sizeof.impl.AgentLoader.loadAgent(AgentLoader.java:119)
	at org.ehcache.sizeof.impl.AgentSizeOf.<clinit>(AgentSizeOf.java:43)
	at org.ehcache.sizeof.SizeOf.newInstance(SizeOf.java:85)
	at org.ehcache.sizeof.SizeOf.newInstance(SizeOf.java:79)
	at org.ehcache.impl.internal.sizeof.DefaultSizeOfEngine.<init>(DefaultSizeOfEngine.java:45)
	at org.ehcache.impl.internal.sizeof.DefaultSizeOfEngineProvider.createSizeOfEngine(DefaultSizeOfEngineProvider.java:61)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$Provider.createStoreInternal(OnHeapStore.java:1727)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$Provider.createStore(OnHeapStore.java:1696)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$Provider.createStore(OnHeapStore.java:1677)
	at org.ehcache.core.EhcacheManager.getStore(EhcacheManager.java:493)
	at org.ehcache.core.EhcacheManager.createNewEhcache(EhcacheManager.java:310)
	at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:259)
	at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:566)
	at org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:72)
	at com.ibm.streamsx.objectstorage.OSObjectRegistry.<init>(OSObjectRegistry.java:146)
	at com.ibm.streamsx.objectstorage.BaseObjectStorageSink.initialize(BaseObjectStorageSink.java:885)
	at com.ibm.streamsx.objectstorage.s3.S3ObjectStorageSink.initialize(S3ObjectStorageSink.java:39)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:736)
	at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:274)
27 Nov 2017 13:53:54.372 [20657] ERROR #splapptrc,J[0],P[0],OSink M[?:com.ibm.streamsx.objectstorage.OSObjectRegistryListener.onEvent:-1]  - Failed to close OSObject with path '//output_2017-11-27T135353.txt'. Error message: s3a://output_2017-11-27T135353.txt is a directory
27 Nov 2017 13:53:54.623 [20657] ERROR #splapptrc,J[0],P[0],OSink M[?:com.ibm.streamsx.objectstorage.OSObjectRegistryListener.onEvent:-1]  - Failed to close OSObject with path '//output_2017-11-27T135353.txt'. Error message: s3a://output_2017-11-27T135353.txt is a directory
27 Nov 2017 13:53:54.990 [20657] ERROR #splapptrc,J[0],P[0],OSink M[?:com.ibm.streamsx.objectstorage.OSObjectRegistryListener.onEvent:-1]  - Failed to close OSObject with path '//output_2017-11-27T135353.txt'. Error message: s3a://output_2017-11-27T135353.txt is a directory

**Comment by markheger** [comment]
Reason: () as osSink = S3ObjectStorageSink(Data) has no output port, but OSObjectRegistryListener is calling fParent.submitOnOutputPort(osObject.getPath(), osObject.getDataSize());
