### ISSUE TITLE
Operator fails in Streaming Analytics service IBM Streams 4.2.4.2 - java.lang.LinkageError

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.objectstorage#74]
Exception in thread "Thread-15" java.lang.BootstrapMethodError: java.lang.LinkageError: loading constraint violation when overriding method "org/ehcache/core/CacheConfigurationChangeListener.cacheConfigurationChange(Lorg/ehcache/core/CacheConfigurationChangeEvent;)V" during creation of class "com/ibm/streamsx/objectstorage/internal/sink/OSObjectCacheEventDispatcher$$Lambda$20/0000000046BB6260": loader "java/lang/InternalAnonymousClassLoader@42e227b8" of class "com/ibm/streamsx/objectstorage/internal/sink/OSObjectCacheEventDispatcher$$Lambda$20/0000000046BB6260" and loader "com/ibm/streams/operator/internal/runtime/api/OperatorClassLoader@a99fa591" of class "org/ehcache/core/CacheConfigurationChangeListener" have different types for the method signature
	at com.ibm.streamsx.objectstorage.internal.sink.OSObjectCacheEventDispatcher.getConfigurationChangeListeners(OSObjectCacheEventDispatcher.java:213)
	at org.ehcache.core.Ehcache.<init>(Ehcache.java:132)
	at org.ehcache.core.Ehcache.<init>(Ehcache.java:116)
	at org.ehcache.config.builders.UserManagedCacheBuilder.build(UserManagedCacheBuilder.java:312)
	at org.ehcache.config.builders.UserManagedCacheBuilder.build(UserManagedCacheBuilder.java:387)
	at com.ibm.streamsx.objectstorage.internal.sink.OSObjectRegistry.<init>(OSObjectRegistry.java:164)
	at com.ibm.streamsx.objectstorage.BaseObjectStorageSink.initialize(BaseObjectStorageSink.java:906)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:736)
	at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:275)
Caused by: java.lang.LinkageError: loading constraint violation when overriding method "org/ehcache/core/CacheConfigurationChangeListener.cacheConfigurationChange(Lorg/ehcache/core/CacheConfigurationChangeEvent;)V" during creation of class "com/ibm/streamsx/objectstorage/internal/sink/OSObjectCacheEventDispatcher$$Lambda$20/0000000046BB6260": loader "java/lang/InternalAnonymousClassLoader@42e227b8" of class "com/ibm/streamsx/objectstorage/internal/sink/OSObjectCacheEventDispatcher$$Lambda$20/0000000046BB6260" and loader "com/ibm/streams/operator/internal/runtime/api/OperatorClassLoader@a99fa591" of class "org/ehcache/core/CacheConfigurationChangeListener" have different types for the method signature
	at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:339)
	at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:206)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:315)
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:833)
	... 9 more

**Comment by markheger** [comment]
There has been an upgrade to Java 9 causing this. IBM Streams 4.2.4.2 is now running with Java IBM J9 VM.

https://github.com/ehcache/ehcache3/issues/2158

Toolkit is using ehcache-3.3.1.jar
-> Need to change the pom.xml to later version of ehcache
