### ISSUE TITLE
java.lang.IllegalArgumentException: The value of property fs.cos.streams-service.iam.endpoint must not be null

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.objectstorage#79]
Get this error (related to #78 ) invoking `ObjectStorageSink`.

I have set the required parameters and `IAMApiKey` and `IAMServiceInstanceId`.

The docs say `IAMTokenEndpoint` has a default.

```
Exception in thread "Thread-14" java.lang.IllegalArgumentException: The value of property fs.cos.streams-service.iam.endpoint must not be null
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
at org.apache.hadoop.conf.Configuration.set(Configuration.java:1142)
at org.apache.hadoop.conf.Configuration.set(Configuration.java:1123)
at com.ibm.streamsx.objectstorage.auth.OSAuthenticationHelper.initCOSAuth(OSAuthenticationHelper.java:77)
at com.ibm.streamsx.objectstorage.auth.OSAuthenticationHelper.configAuthProperties(OSAuthenticationHelper.java:42)
at com.ibm.streamsx.objectstorage.client.ObjectStorageCOSClient.initClientConfig(ObjectStorageCOSClient.java:35)
at com.ibm.streamsx.objectstorage.client.ObjectStorageAbstractClient.<init>(ObjectStorageAbstractClient.java:49)
at com.ibm.streamsx.objectstorage.client.ObjectStorageAbstractClient.<init>(ObjectStorageAbstractClient.java:57)
at com.ibm.streamsx.objectstorage.client.ObjectStorageCOSClient.<init>(ObjectStorageCOSClient.java:25)
at com.ibm.streamsx.objectstorage.client.ObjectStorageClientFactory.getObjectStorageClient(ObjectStorageClientFactory.java:23)
at com.ibm.streamsx.objectstorage.AbstractObjectStorageOperator.createObjectStorageClient(AbstractObjectStorageOperator.java:184)
at com.ibm.streamsx.objectstorage.AbstractObjectStorageOperator.initialize(AbstractObjectStorageOperator.java:94)
at com.ibm.streamsx.objectstorage.BaseObjectStorageSink.initialize(BaseObjectStorageSink.java:781)
at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:736)
at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:274)
```

**Comment by ddebrunner** [comment]
The doc:
```
IAMTokenEndpoint
Specifies IAM token endpoint. Relevant for IAM authentication case only. Default value is 'https://iam.bluemix.net/oidc/token'.
```

**Comment by ddebrunner** [comment]
However, if I set `IAMTokenEndpoint`  to value shown, I got further (and hit a different error).
